CREATE DATABASE listatarefas;

USE listatarefas;

CREATE TABLE tb_tarefas(
	id int AUTO INCREMENT PRIMARY KEY,
	TITULO VARCHAR(100),
	DESCRICAO VARCHAR(255),
	SITUACAO BOOLEAN
)

ALTER TABLE tb_tarefas ADD STATUS VARCHAR(20);

ALTER TABLE tb_tarefas
CHANGE SITUACAO ATIVO TINYINT(1) DEFAULT 1;